# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.2972e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3049, 0.0140, 0.6293],
        [0.7741, 0.3268, 0.0844],
        [0.9594, 0.5329, 0.8954],
        [0.3111, 0.4141, 0.7798],
        [0.0289, 0.3163, 0.9733]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.3049, 0.0140, 0.6293],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.3111, 0.4141, 0.7798],
        [0.0289, 0.3163, 0.9733]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
# 1
torch.Tensor(2, 17)

tensor([[ 1.3014e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  1.2953e-35,  0.0000e+00,  5.0873e-36,
          0.0000e+00, -3.8922e+33],
        [ 4.5800e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [7]:
# 2
torch.FloatTensor(3, 1)

tensor([[1.2972e-35],
        [0.0000e+00],
        [1.5975e-43]])

In [10]:
# 3
A = torch.LongTensor(5, 2, 1)
A[:] = 7

print(A)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [20]:
# 4
B = torch.ByteTensor(5,)
B[1:4] = 1

print(B)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.4380, 0.4261, 0.7147],
        [2.1674, 2.8251, 2.3589],
        [2.2869, 2.1313, 2.5628],
        [0.4402, 0.8874, 1.5560],
        [0.4156, 0.6114, 1.0051]])


### 2.2 Addition: syntax 2

In [22]:
print(torch.add(x, y))

tensor([[0.4380, 0.4261, 0.7147],
        [2.1674, 2.8251, 2.3589],
        [2.2869, 2.1313, 2.5628],
        [0.4402, 0.8874, 1.5560],
        [0.4156, 0.6114, 1.0051]])


### 2.3 Addition: giving an output tensor

In [23]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4380, 0.4261, 0.7147],
        [2.1674, 2.8251, 2.3589],
        [2.2869, 2.1313, 2.5628],
        [0.4402, 0.8874, 1.5560],
        [0.4156, 0.6114, 1.0051]])


### 2.4 Addition: in-place

adds `x`to `y`

In [24]:
y.add_(x)
print(y)

tensor([[0.4380, 0.4261, 0.7147],
        [2.1674, 2.8251, 2.3589],
        [2.2869, 2.1313, 2.5628],
        [0.4402, 0.8874, 1.5560],
        [0.4156, 0.6114, 1.0051]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [25]:
print(x[:, 1])

tensor([0.0140, 2.0000, 2.0000, 0.4141, 0.3163])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [26]:
# 1)
torch.Tensor.mul(x,y)

tensor([[0.1335, 0.0060, 0.4497],
        [4.3348, 5.6502, 4.7179],
        [4.5738, 4.2625, 5.1256],
        [0.1369, 0.3675, 1.2133],
        [0.0120, 0.1934, 0.9783]])

In [27]:
# 2)
y.mul_(x)

tensor([[0.1335, 0.0060, 0.4497],
        [4.3348, 5.6502, 4.7179],
        [4.5738, 4.2625, 5.1256],
        [0.1369, 0.3675, 1.2133],
        [0.0120, 0.1934, 0.9783]])

In [28]:
# 3)
torch.Tensor.div(x,y)

tensor([[2.2833, 2.3470, 1.3993],
        [0.4614, 0.3540, 0.4239],
        [0.4373, 0.4692, 0.3902],
        [2.2718, 1.1269, 0.6427],
        [2.4064, 1.6355, 0.9949]])

In [34]:
# 4)
C = torch.Tensor(2,4)
D = torch.Tensor(4,2)

torch.matmul(C,D)

tensor([[       nan, 4.1763e-14],
        [       nan, 4.9357e-14]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [40]:
# 1)
A = torch.ones(5, 2)
print(A)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [42]:
# 2)
B = A.numpy()
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [44]:
# 3)
C = torch.from_numpy(B)
print(C)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [45]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
